spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database: MYSQL

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://sl-aus-syd-1-portal.1.dblayer.com:16748/compose?autoReconnect=true&useSSL=true
    username: admin
    password: DECBXHKNTXAGMXYC